FROM ubuntu:latest

MAINTAINER kermit "kermitpurple96@gmail.com"

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install -y net-tools \
    sudo \
    iputils-ping \
    iproute2 \
    neovim \
    moreutils \
    curl \
    git \ 
    nano \
    apache2 \
    php \
    openssh-server \
    ufw

RUN mkdir /usr/share/scripts

COPY rockyou.txt /usr/share/scripts
COPY grepScript.py /usr/share/scripts
COPY uniqScript.py /usr/share/scripts
COPY diffScript.py /usr/share/scripts
COPY awkScript.py /usr/share/scripts
COPY chattr.sh /usr/share/scripts

RUN useradd -ms /bin/bash mini1 
RUN touch /home/mini1/challenge_1.txt
RUN chmod -R 750 /home/mini1
RUN ln -sf /dev/null /home/mini1/.bash_history
RUN rm /home/mini1/.bashrc
COPY entorno_bashrc1 /home/mini1/.bashrc

RUN useradd -ms /bin/bash mini2 
RUN touch /home/mini2/challenge_2.txt
RUN chmod -R 750 /home/mini2
RUN ln -sf /dev/null /home/mini2/.bash_history
RUN rm /home/mini2/.bashrc
COPY entorno_bashrc2 /home/mini2/.bashrc


RUN useradd -ms /bin/bash mini3 
RUN touch /home/mini3/challenge_3a.txt
RUN touch /home/mini3/challenge_3b.txt
RUN chmod -R 750 /home/mini3
RUN ln -sf /dev/null /home/mini3/.bash_history
RUN rm /home/mini3/.bashrc
COPY entorno_bashrc3 /home/mini3/.bashrc


RUN useradd -ms /bin/bash mini4 
RUN touch /home/mini4/challenge_4.txt
RUN chmod -R 750 /home/mini4
RUN ln -sf /dev/null /home/mini4/.bash_history
RUN rm /home/mini4/.bashrc
COPY entorno_bashrc4 /home/mini4/.bashrc


RUN python3 /usr/share/scripts/grepScript.py
RUN python3 /usr/share/scripts/uniqScript.py
RUN python3 /usr/share/scripts/diffScript.py
RUN python3 /usr/share/scripts/awkScript.py

RUN sudo echo 'mini1:frog' | chpasswd
RUN sudo echo 'mini2:gDqOpl5RI4rLHcUk97NFwP0av' | chpasswd
RUN sudo echo 'mini3:hd6QWmX7AtHxf3GK5IJ0CN4Mo' | chpasswd
RUN sudo echo 'mini4:9H6iOx3ILdcFp2S4mVuyAhUkE' | chpasswd
RUN sudo chmod -R 700 /usr/share/scripts 

EXPOSE 22 

ENTRYPOINT service ssh start && /bin/bash


