FROM nginx

MAINTAINER kermit "kermitpurple96@gmail.com"

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install -y net-tools \
    sudo \
    netcat \
    wget \
    socat \
    iputils-ping \
    iproute2 \
    neovim \
    moreutils \
    curl \
    git \
    nano \
    apache2 \
    php \
    openssh-server \
    ufw

RUN mkdir /usr/share/scripts
COPY task.sh /usr/share/scripts/task.sh

RUN useradd -ms /bin/bash mini1 
RUN chmod -R 750 /home/mini1
RUN ln -sf /dev/null /home/mini1/.bash_history
RUN rm /home/mini1/.bashrc
COPY entorno_bashrc1 /home/mini1/.bashrc

RUN sudo echo 'mini1:frog' | chpasswd
RUN sudo chmod -R 700 /usr/share/scripts
RUN sudo /bin/bash /usr/share/scripts/task.sh
RUN echo '15tRvbhU4G9uFBYZ3JCVrf7zP' > /usr/share/nginx/html/index.html

EXPOSE 22 
EXPOSE 7777
EXPOSE 10432

ENTRYPOINT service nginx start && /bin/bash


