FROM nginx

MAINTAINER kermit "kermitpurple96@gmail.com"

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install -y net-tools \
    sudo \
    netcat \
    wget \
    socat \
    iputils-ping \
    iproute2 \
    neovim \
    moreutils \
    curl \
    git \
    nano \
    apache2 \
    php \
    openssh-server \
    mysql-client \
    ufw

RUN mkdir /usr/share/scripts

COPY default.conf /etc/nginx/conf.d/default.conf

RUN useradd -ms /bin/bash mini1 
RUN chmod -R 750 /home/mini1
RUN ln -sf /dev/null /home/mini1/.bash_history
RUN rm /home/mini1/.bashrc
COPY entorno_bashrc1 /home/mini1/.bashrc

RUN useradd -ms /bin/bash mini2 
RUN chmod -R 750 /home/mini2
RUN ln -sf /dev/null /home/mini2/.bash_history
RUN rm /home/mini2/.bashrc
COPY entorno_bashrc2 /home/mini2/.bashrc

RUN useradd -ms /bin/bash mini3 
RUN chmod -R 750 /home/mini3
RUN ln -sf /dev/null /home/mini3/.bash_history
RUN rm /home/mini3/.bashrc
COPY entorno_bashrc3 /home/mini3/.bashrc

RUN sudo echo 'mini1:frog' | chpasswd
RUN sudo echo 'mini2:T0ipt5K8k31dmNMDOH4WsxeV9' | chpasswd
RUN sudo echo 'mini3:7OJcptMElsG3rVPqSWdz6ouN1' | chpasswd
RUN sudo chmod -R 700 /usr/share/scripts

EXPOSE 22 
EXPOSE 3429

ENTRYPOINT service nginx start && service ssh start && /bin/bash


