FROM nginx

MAINTAINER kermit "kermitpurple96@gmail.com"

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install -y net-tools \
    sudo \
    iputils-ping \
    iproute2 \
    neovim \
    moreutils \
    curl \
    git \
    nano \
    apache2 \
    php \
    openssh-server \
    ufw

RUN mkdir /usr/share/scripts

COPY default.conf /etc/nginx/conf.d/default.conf

RUN useradd -ms /bin/bash mini1 
RUN chmod -R 750 /home/mini1
RUN ln -sf /dev/null /home/mini1/.bash_history
RUN rm /home/mini1/.bashrc
COPY entorno_bashrc1 /home/mini1/.bashrc

RUN sudo echo 'mini1:frog' | chpasswd
RUN sudo chmod -R 700 /usr/share/scripts

EXPOSE 22 

ENTRYPOINT service ssh start && service nginx start && /bin/bash


