version: "3.9"
services:
  entorno:
    build: .
    image: entorno
    ports:
      - "6000:22"
    stdin_open: true
    tty: true
    cap_add:
      - LINUX_IMMUTABLE
    entrypoint: [ "bash", "-c", "/usr/share/scripts/chattr.sh && service ssh start && /bin/bash"]
    networks: 
      minihack:
        ipv4_address: 10.10.10.2

  archivos: 
    build: .
    image: archivos
    ports:
      - "8000:22"
    stdin_open: true
    tty: true
    cap_add:
      - LINUX_IMMUTABLE
    volumes:
      - ./archivos/archivos3.txt:/mnt/archivos3.txt
    entrypoint: [ "bash", "-c", "/usr/share/scripts/archivos1.sh && service ssh start && /bin/bash"]
    networks:
      minihack:
        ipv4_address: 10.10.10.3

  procesos:
    build: .
    image: procesos
    ports: 
      - "8500:22"
    stdin_open: true
    tty: true
    cap_add:
      - LINUX_IMMUTABLE
    entrypoint: ["bash", "-c", "service ssh start && service nginx start && /bin/bash"]
    networks: 
      minihack:
        ipv4_address: 10.10.10.4
 
  ftp:
    container_name: ftp-server
    image: garethflowers/ftp-server
    environment:
      - FTP_USER=${FTP_USERNAME}
      - FTP_PASS=${FTP_PASSWORD}
    restart: always
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'   # passive mode
    volumes:
        - ./ftpflag:/home/${FTP_USERNAME}/shared 
    networks:
      minihack:
        ipv4_address: 10.10.10.5

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=minihack
      - MYSQL_ROOT_PASSWORD=FlipperZero@0
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      minihack:
        ipv4_address: 10.10.10.6

 
  usuarios:
    build: .
    image: usuarios
    ports:
      - "7000:22"
    stdin_open: true
    tty: true
    cap_add:
      - LINUX_IMMUTABLE
    entrypoint: [ "bash", "-c", "/usr/share/scripts/chattr.sh && service ssh start && /bin/bash"]
    networks: 
      minihack:
        ipv4_address: 10.10.10.7

  pivote:
    build: .
    image: pivote
    ports:
      - "9000:22"
    stdin_open: true
    tty: true
    cap_add:
      - LINUX_IMMUTABLE
    entrypoint: [ "bash", "-c", "service ssh start && /bin/bash"]
    networks: 
      minihack:
        ipv4_address: 10.10.10.8

  networking:
    build: .
    image: networking
    ports: 
      - "7500:22"
    stdin_open: true
    tty: true
    cap_add:
      - LINUX_IMMUTABLE
    entrypoint: []
    networks: 
      minihack:
        ipv4_address: 10.10.10.9
    entrypoint: ["bash", "-c", "/usr/share/scripts/task.sh && service nginx start && /bin/bash"]
  
  comandos:
    build: .
    image: comandos
    ports: 
      - "6500:22"
    stdin_open: true
    tty: true
    cap_add:
      - LINUX_IMMUTABLE
    entrypoint: []
    networks: 
      minihack:
        ipv4_address: 10.10.10.10
    entrypoint: ["bash", "-c", "/usr/share/scripts/chattr.sh && service ssh start && /bin/bash"]
 
networks:
  minihack:
    ipam:
      driver: default
      config:
        - subnet: "10.10.10.0/24"

