version: "3.9"
services:
  entorno:
    build: .
    image: entorno
    ports:
      - "7000:22"
    stdin_open: true
    tty: true
    cap_add:
      - LINUX_IMMUTABLE
    entrypoint: [ "bash", "-c", "/usr/share/scripts/chattr.sh && service ssh start && /bin/bash"]      