version: "3.9"
services:
  entorno:
    build: .
    image: entorno
    ports:
      - "6000:22"
    stdin_open: true
    tty: true
    cap_add:
      - LINUX_IMMUTABLE
    entrypoint: [ "bash", "-c", "/usr/share/scripts/chattr.sh && service ssh start && /bin/bash"]
    networks: 
      - minihack

  archivos: 
    build: .
    image: archivos
    ports:
      - "8000:22"
    stdin_open: true
    tty: true
    cap_add:
      - LINUX_IMMUTABLE
    entrypoint: [ "bash", "-c", "/usr/share/scripts/archivos1.sh && service ssh start && /bin/bash"]     
    volumes:
      - ./archivos/archivos3.txt:/mnt/archivos3.txt
    networks:
      - minihack

  procesos:
    build: .
    image: procesos
    ports: 
      - "8500:22"
    stdin_open: true
    tty: true
    cap_add:
      - LINUX_IMMUTABLE
    entrypoint: []
    networks: 
      - minihack
    entrypoint: ["bash", "-c", "service ssh start && service nginx start && /bin/bash"]
  ftp:
    container_name: ftp-server
    image: garethflowers/ftp-server
    environment:
      - FTP_USER=${FTP_USERNAME}
      - FTP_PASS=${FTP_PASSWORD}
    restart: always
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'   # passive mode
    volumes:
        - ./ftpflag:/home/${FTP_USERNAME}/shared 
  
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=minihack
      - MYSQL_ROOT_PASSWORD=FlipperZero@0
    networks: 
      - minihack
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  minihack:
    ipam:
      driver: default
      config:
        - subnet: "10.10.10.0/24"

