FROM ubuntu:latest

MAINTAINER kermit "kermitpurple96@gmail.com"

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install -y net-tools \
    sudo \
    iputils-ping \
    iproute2 \
    neovim \
    moreutils \
    curl \
    git \ 
    nano \
    apache2 \
    php \
    openssh-server \
    ufw

RUN mkdir /usr/share/scripts

COPY chattr.sh /usr/share/scripts

RUN useradd -ms /bin/bash mini1 
RUN useradd -ms /bin/bash mini2 
RUN touch /home/mini1/challenge_1.txt
RUN echo 'KNR1ElmgX7IcHqfD96QuZvnUr' > /home/mini1/challenge_1.txt
RUN chown mini2:mini2 /home/mini1/challenge_1.txt
RUN chown mini2:mini2 /usr/bin/find
RUN chmod -R 750 /home/mini1
RUN chmod 4711 /usr/bin/find
RUN ln -sf /dev/null /home/mini1/.bash_history
RUN rm /home/mini1/.bashrc
COPY entorno_bashrc1 /home/mini1/.bashrc
 
RUN chmod -R 750 /home/mini2
RUN ln -sf /dev/null /home/mini2/.bash_history
RUN rm /home/mini2/.bashrc
COPY entorno_bashrc2 /home/mini2/.bashrc
RUN groupadd dG5IuCMbOsf2qe6TEoyFmAaYZ
RUN usermod -a -G dG5IuCMbOsf2qe6TEoyFmAaYZ mini2

RUN useradd -ms /bin/bash mini3 
RUN touch /home/mini3/challenge_3.txt
RUN chmod -R 750 /home/mini3
RUN ln -sf /dev/null /home/mini3/.bash_history
RUN rm /home/mini3/.bashrc
COPY entorno_bashrc3 /home/mini3/.bashrc
RUN touch /home/mini3/challenge_3.txt
RUN chmod 2356 /home/mini3/challenge_3.txt

RUN sudo echo 'mini1:frog' | chpasswd
RUN sudo echo 'mini2:LM7C8kBESJxVe3pAbzvI4rDF5' | chpasswd
RUN sudo echo 'mini3:xGi50EWz29DkuYsBepq1PbTrV' | chpasswd
RUN sudo chmod -R 700 /usr/share/scripts 

EXPOSE 22 

ENTRYPOINT service ssh start && /bin/bash


