FROM ubuntu:latest

MAINTAINER kermit "kermitpurple96@gmail.com"

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install -y net-tools \
    sudo \
    iputils-ping \
    iproute2 \
    neovim \
    moreutils \
    curl \
    git \ 
    nano \
    apache2 \
    php \
    openssh-server \
    ufw

RUN mkdir /usr/share/scripts
COPY archivos1.sh /usr/share/scripts

RUN touch /var/mail/secret.txt
COPY archivos2.txt /var/mail/secret.txt

RUN useradd -ms /bin/bash mini1 
RUN chmod -R 750 /home/mini1
RUN ln -sf /dev/null /home/mini1/.bash_history
RUN rm /home/mini1/.bashrc
COPY entorno_bashrc1 /home/mini1/.bashrc

RUN useradd -ms /bin/bash mini2 
RUN chmod -R 750 /home/mini2
RUN ln -sf /dev/null /home/mini2/.bash_history
RUN rm /home/mini2/.bashrc
COPY entorno_bashrc2 /home/mini2/.bashrc

RUN useradd -ms /bin/bash mini3 
RUN chmod -R 750 /home/mini3
RUN ln -sf /dev/null /home/mini3/.bash_history
RUN rm /home/mini3/.bashrc
COPY entorno_bashrc3 /home/mini3/.bashrc

RUN sudo echo 'mini1:frog' | chpasswd
RUN sudo echo 'mini2:t0KSLJE4WGzl8BPmkMxHbsd25' | chpasswd
RUN sudo echo 'mini3:jpZ7GYn2NIKUxtTzfF9CcAPE1' | chpasswd
RUN sudo chmod 744 /var/mail/secret.txt
RUN sudo chmod -R 700 /usr/share/scripts
RUN sudo chmod 740 /etc/hosts
RUN sudo chown root:mini1 /etc/hosts
RUN sudo chmod 740 /var/mail/secret.txt
RUN sudo chown root:mini2 /var/mail/secret.txt
 

EXPOSE 22 

ENTRYPOINT service ssh start && /bin/bash


